# ?? ????? ?? ?? ??
server:
  port: 0

# ?? ????? ?? ??
spring:
  application:
    name: user-service

# ?? ????? eureka ??
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # eureka ?? ??
    fetch-registry: true # eureka ????? ?????? ??? ????? ??? ???
    service-url:     # ??? ??? ???? ??? ??.. ??? ??? ?? ?? ??..
      defaultZone: http://127.0.0.1:8761/eureka # ? ?? ??????? ??? ?????.


