# ?? ????? ?? ?? ??
server:
  port: 0

# ?? ????? ?? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/villion_user?serverTimezone=Asia/Seoul?useSSL=false
    username: root
    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  application:
    name: user-service

# ?? ????? eureka ??
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # eureka ?? ??
    fetch-registry: true # eureka ????? ?????? ??? ????? ??? ???
    service-url:     # ??? ??? ???? ??? ??.. ??? ??? ?? ?? ??..
      defaultZone: http://127.0.0.1:8761/eureka # ? ?? ??????? ??? ?????.


